### ISSUE TITLE
CRC may fail?

### ISSUE THREAD

**Issue by coolacid** [VE3LSR/pyax25#3]
```
Traceback (most recent call last):
  File "./pelmorex.py", line 54, in <module>
    run()
  File "./pelmorex.py", line 30, in run
    x.sendBulletin("VE3LSR Weather Alerting Started", "WXZ")
  File "/home/Repos/CoolAcid/NAADAlerts/pyax25/pyax25/ax25.py", line 92, in sendBulletin
    self.buildPacket(message=message)
  File "/home/Repos/CoolAcid/NAADAlerts/pyax25/pyax25/ax25.py", line 76, in buildPacket
    crc = self.calc_crc(packet)
  File "/home/Repos/CoolAcid/NAADAlerts/pyax25/pyax25/ax25.py", line 61, in calc_crc
    return (crc).bytes
  File "/usr/local/lib/python3.6/dist-packages/bitstring.py", line 1347, in _getbytes
    raise InterpretError("Cannot interpret as bytes unambiguously - "
bitstring.InterpretError: Cannot interpret as bytes unambiguously - not multiple of 8 bits.
```

**Comment by coolacid** [comment]
1181f214ea017d51580192134fa79360e8c4cd69 might have fixed this issue.
